'use client';
import { useState, useRef, useCallback } from 'react';
import Link from 'next/link';
import Navbar from '../../../components/Navbar';
import Button from '../../../components/Button';
import Badge from '../../../components/Badge';
import styles from './create.module.css';

/* ──────────────────────────────────────────────
   Mock Questions (generated by Gemma)
────────────────────────────────────────────── */
const MOCK_QUESTIONS = [
  {
    id: 1,
    type: 'MCQ',
    question: 'Which of the following is the primary pigment responsible for photosynthesis?',
    options: ['Carotenoid', 'Chlorophyll', 'Xanthophyll', 'Anthocyanin'],
    answer: 'Chlorophyll',
    marks: 2,
    difficulty: 'Easy',
  },
  {
    id: 2,
    type: 'MCQ',
    question: 'In the Calvin cycle, how many ATP molecules are consumed per CO₂ molecule fixed?',
    options: ['1', '2', '3', '4'],
    answer: '3',
    marks: 3,
    difficulty: 'Hard',
  },
  {
    id: 3,
    type: 'True/False',
    question: 'The light-dependent reactions of photosynthesis occur in the stroma of the chloroplast.',
    answer: 'False',
    marks: 1,
    difficulty: 'Easy',
  },
  {
    id: 4,
    type: 'True/False',
    question: 'Oxygen is released as a by-product of the light-dependent reactions.',
    answer: 'True',
    marks: 1,
    difficulty: 'Easy',
  },
  {
    id: 5,
    type: 'One-liner',
    question: 'What is the role of NADPH in the Calvin cycle?',
    answer: 'NADPH provides the reducing power (electrons) to convert 3-phosphoglycerate into G3P.',
    marks: 2,
    difficulty: 'Medium',
  },
  {
    id: 6,
    type: 'Brief Answer',
    question: 'Explain the significance of the photorespiration process and its impact on plant productivity.',
    answer: 'Photorespiration occurs when RuBisCO fixes O₂ instead of CO₂, producing glycolate and reducing overall photosynthetic efficiency. It is more common in hot, dry conditions and leads to lower crop yields in C3 plants.',
    marks: 5,
    difficulty: 'Hard',
  },
  {
    id: 7,
    type: 'MCQ',
    question: 'Which of the following organisms perform anoxygenic photosynthesis?',
    options: ['Plants', 'Cyanobacteria', 'Purple sulfur bacteria', 'Algae'],
    answer: 'Purple sulfur bacteria',
    marks: 2,
    difficulty: 'Medium',
  },
  {
    id: 8,
    type: 'Brief Answer',
    question: 'Compare and contrast C3 and C4 photosynthesis pathways.',
    answer: 'C3 plants fix CO₂ directly via RuBisCO producing 3-phosphoglycerate as the first stable product. C4 plants have an additional mechanism using PEP carboxylase in mesophyll cells to concentrate CO₂ around RuBisCO in bundle sheath cells, reducing photorespiration.',
    marks: 5,
    difficulty: 'Hard',
  },
];

/* ──────────────────────────────────────────────
   Gemma Loading Steps
────────────────────────────────────────────── */
const GEMMA_STEPS = [
  { icon: '🔍', label: 'Analyzing your syllabus content...' },
  { icon: '💡', label: 'Generating questions based on objectives...' },
  { icon: '⚖️', label: 'Balancing question difficulty levels...' },
  { icon: '✨', label: 'Preparing your assessment...' },
];

/* ──────────────────────────────────────────────
   Step Indicator
────────────────────────────────────────────── */
function StepIndicator({ currentStep }) {
  const steps = ['Upload Syllabus', 'Configure Test', 'Generate & Review'];
  return (
    <div className={styles.stepIndicator}>
      {steps.map((label, i) => (
        <div key={i} className={styles.stepItem}>
          <div className={`${styles.stepDot} ${i < currentStep ? styles.stepDone : i === currentStep ? styles.stepActive : styles.stepFuture}`}>
            {i < currentStep ? '✓' : i + 1}
          </div>
          <span className={`${styles.stepLabel} ${i === currentStep ? styles.stepLabelActive : ''}`}>{label}</span>
          {i < steps.length - 1 && <div className={`${styles.stepLine} ${i < currentStep ? styles.stepLineDone : ''}`} />}
        </div>
      ))}
    </div>
  );
}

/* ──────────────────────────────────────────────
   Step 1 – Upload
────────────────────────────────────────────── */
function UploadStep({ onNext }) {
  const [dragActive, setDragActive] = useState(false);
  const [file, setFile] = useState(null);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [uploading, setUploading] = useState(false);
  const inputRef = useRef(null);

  const handleFile = (f) => {
    if (!f || f.type !== 'application/pdf') return;
    setFile(f);
    setUploading(true);
    setUploadProgress(0);
    let progress = 0;
    const interval = setInterval(() => {
      progress += Math.random() * 20;
      if (progress >= 100) {
        progress = 100;
        clearInterval(interval);
        setUploading(false);
      }
      setUploadProgress(Math.min(Math.round(progress), 100));
    }, 200);
  };

  const onDrop = useCallback((e) => {
    e.preventDefault();
    setDragActive(false);
    handleFile(e.dataTransfer.files[0]);
  }, []);

  const onDragOver = (e) => { e.preventDefault(); setDragActive(true); };
  const onDragLeave = () => setDragActive(false);

  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepTitle}>Upload Your Syllabus</h2>
      <p className={styles.stepDesc}>Upload a PDF of your syllabus and Gemma will intelligently extract topics and learning objectives.</p>

      {/* Drop Zone */}
      <div
        className={`${styles.dropZone} ${dragActive ? styles.dropZoneActive : ''} ${file ? styles.dropZoneSuccess : ''}`}
        onDrop={onDrop}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        onClick={() => !file && inputRef.current?.click()}
      >
        <input ref={inputRef} type="file" accept=".pdf" style={{ display: 'none' }} onChange={e => handleFile(e.target.files[0])} />
        {file ? (
          <div className={styles.filePreview}>
            <div className={styles.filePdfIcon}>📄</div>
            <div className={styles.fileDetails}>
              <span className={styles.fileName}>{file.name}</span>
              <span className={styles.fileSize}>{(file.size / 1024).toFixed(1)} KB · PDF</span>
            </div>
            {uploading ? (
              <div className={styles.uploadStatus}>
                <div className={styles.uploadBarWrapper}>
                  <div className={styles.uploadBar} style={{ width: `${uploadProgress}%` }} />
                </div>
                <span className={styles.uploadPct}>{uploadProgress}%</span>
              </div>
            ) : (
              <span className={styles.uploadDone}>✅ Uploaded</span>
            )}
          </div>
        ) : (
          <>
            <div className={styles.dropIcon}>📂</div>
            <p className={styles.dropText}>Drag & drop your syllabus PDF here</p>
            <p className={styles.dropSub}>or</p>
            <button className={styles.browseBtn} onClick={e => { e.stopPropagation(); inputRef.current?.click(); }}>
              Browse File
            </button>
            <p className={styles.dropHint}>Supports PDF files up to 20 MB</p>
          </>
        )}
      </div>

      <div className={styles.stepActions}>
        <Button variant="primary" disabled={!file || uploading} onClick={onNext}>
          Continue to Configuration →
        </Button>
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────
   Step 2 – Configuration
────────────────────────────────────────────── */
function ConfigStep({ onNext, onBack }) {
  const [types, setTypes] = useState({ MCQ: true, TrueFalse: false, OneLiner: false, BriefAnswer: false });
  const [marks, setMarks] = useState(20);
  const [duration, setDuration] = useState(30);

  const toggleType = (key) => setTypes(prev => ({ ...prev, [key]: !prev[key] }));
  const anySelected = Object.values(types).some(Boolean);

  return (
    <div className={styles.stepContent}>
      <h2 className={styles.stepTitle}>Configure Your Test</h2>
      <p className={styles.stepDesc}>Choose question types, marks, and duration before Gemma generates your assessment.</p>

      {/* Question Types */}
      <div className={styles.configSection}>
        <h3 className={styles.configLabel}>Question Types</h3>
        <div className={styles.checkboxGrid}>
          {[
            { key: 'MCQ', label: 'Multiple Choice (MCQ)', icon: '🔘' },
            { key: 'TrueFalse', label: 'True / False', icon: '✅' },
            { key: 'OneLiner', label: 'One-liner Answer', icon: '✏️' },
            { key: 'BriefAnswer', label: 'Brief Answer', icon: '📝' },
          ].map(({ key, label, icon }) => (
            <label key={key} className={`${styles.checkCard} ${types[key] ? styles.checkCardActive : ''}`}>
              <input type="checkbox" checked={types[key]} onChange={() => toggleType(key)} className={styles.hiddenCheck} />
              <span className={styles.checkIcon}>{icon}</span>
              <span className={styles.checkLabel}>{label}</span>
              <span className={`${styles.checkMark} ${types[key] ? styles.checkMarkActive : ''}`}>
                {types[key] ? '✓' : ''}
              </span>
            </label>
          ))}
        </div>
      </div>

      {/* Total Marks */}
      <div className={styles.configSection}>
        <h3 className={styles.configLabel}>Total Marks</h3>
        <div className={styles.marksRow}>
          {[10, 20, 30, 50, 100].map(m => (
            <button key={m} className={`${styles.marksBtn} ${marks === m ? styles.marksBtnActive : ''}`} onClick={() => setMarks(m)}>
              {m}
            </button>
          ))}
          <div className={styles.marksCustom}>
            <input
              type="number"
              min="1" max="500"
              value={marks}
              onChange={e => setMarks(Number(e.target.value))}
              className={styles.marksInput}
            />
            <span style={{ color: 'var(--color-text-muted)', fontSize: '0.85rem' }}>marks</span>
          </div>
        </div>
      </div>

      {/* Duration */}
      <div className={styles.configSection}>
        <h3 className={styles.configLabel}>Duration</h3>
        <div className={styles.durationRow}>
          {[15, 30, 60].map(d => (
            <button key={d} className={`${styles.durationBtn} ${duration === d ? styles.durationBtnActive : ''}`} onClick={() => setDuration(d)}>
              {d} min
            </button>
          ))}
        </div>
      </div>

      <div className={styles.stepActions}>
        <Button variant="secondary" onClick={onBack}>← Back</Button>
        <Button variant="primary" disabled={!anySelected} onClick={onNext}>
          Generate with Gemma ✨
        </Button>
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────
   Gemma Generation Screen
────────────────────────────────────────────── */
function GemmaGeneration({ onDone }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [done, setDone] = useState(false);

  useState(() => {
    const timers = GEMMA_STEPS.map((_, i) =>
      setTimeout(() => {
        setCurrentStep(i);
        if (i === GEMMA_STEPS.length - 1) {
          setTimeout(() => { setDone(true); onDone(); }, 1200);
        }
      }, i * 1400)
    );
    return () => timers.forEach(clearTimeout);
  }, []);

  return (
    <div className={styles.gemmaScreen}>
      {/* Gemma branding */}
      <div className={styles.gemmaLogo}>
        <div className={styles.gemmaOrb} />
        <div className={styles.gemmaTitle}>
          <span className={styles.gemmaBrand}>Gemma</span>
          <span className={styles.gemmaBy}>by Google</span>
        </div>
      </div>

      <h2 className={styles.gemmaHeading}>Crafting your assessment</h2>
      <p className={styles.gemmaSubHeading}>Our AI is at work — please wait a moment.</p>

      {/* Steps */}
      <div className={styles.gemmaSteps}>
        {GEMMA_STEPS.map((step, i) => (
          <div key={i} className={`${styles.gemmaStep} ${i <= currentStep ? styles.gemmaStepActive : ''} ${i < currentStep ? styles.gemmaStepDone : ''}`}>
            <div className={styles.gemmaStepIcon}>
              {i < currentStep ? '✓' : i === currentStep ? <span className={styles.gemmaPulse}>●</span> : '○'}
            </div>
            <span className={styles.gemmaStepLabel}>{step.label}</span>
          </div>
        ))}
      </div>

      {/* Animated progress bar */}
      <div className={styles.gemmaProgressWrapper}>
        <div
          className={styles.gemmaProgressBar}
          style={{ width: `${((currentStep + 1) / GEMMA_STEPS.length) * 100}%` }}
        />
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────
   Question Card (Review)
────────────────────────────────────────────── */
function QuestionCard({ q, index, onDelete, onRegenerate }) {
  const [editing, setEditing] = useState(false);
  const [text, setText] = useState(q.question);

  const diffColor = q.difficulty === 'Hard' ? '#ef4444' : q.difficulty === 'Medium' ? '#f59e0b' : '#10b981';

  return (
    <div className={styles.qCard}>
      <div className={styles.qCardHeader}>
        <div className={styles.qMeta}>
          <span className={styles.qIndex}>Q{index + 1}</span>
          <span className={styles.qTypeBadge}>{q.type}</span>
          <span className={styles.qDiff} style={{ color: diffColor, background: diffColor + '18' }}>
            {q.difficulty}
          </span>
          <span className={styles.qMarks}>{q.marks} mark{q.marks > 1 ? 's' : ''}</span>
        </div>
        <div className={styles.qActions}>
          <button className={styles.qActionBtn} title="Edit" onClick={() => setEditing(e => !e)}>✏️</button>
          <button className={styles.qActionBtn} title="Regenerate" onClick={onRegenerate}>🔄</button>
          <button className={`${styles.qActionBtn} ${styles.qActionDanger}`} title="Delete" onClick={onDelete}>🗑</button>
        </div>
      </div>

      {editing ? (
        <textarea
          className={styles.qEditArea}
          value={text}
          onChange={e => setText(e.target.value)}
          onBlur={() => setEditing(false)}
          autoFocus
          rows={3}
        />
      ) : (
        <p className={styles.qText}>{text}</p>
      )}

      {q.type === 'MCQ' && (
        <div className={styles.qOptions}>
          {q.options.map((opt, i) => (
            <div key={i} className={`${styles.qOption} ${opt === q.answer ? styles.qOptionCorrect : ''}`}>
              <span className={styles.qOptionLetter}>{String.fromCharCode(65 + i)}</span>
              {opt}
              {opt === q.answer && <span className={styles.qOptionMark}>✓</span>}
            </div>
          ))}
        </div>
      )}

      {q.type === 'True/False' && (
        <div className={styles.qOptions}>
          {['True', 'False'].map(v => (
            <div key={v} className={`${styles.qOption} ${v === q.answer ? styles.qOptionCorrect : ''}`}>
              <span className={styles.qOptionLetter}>{v === 'True' ? 'T' : 'F'}</span>
              {v}
              {v === q.answer && <span className={styles.qOptionMark}>✓</span>}
            </div>
          ))}
        </div>
      )}

      {(q.type === 'One-liner' || q.type === 'Brief Answer') && (
        <div className={styles.qAnswer}>
          <span className={styles.qAnswerLabel}>Sample Answer:</span>
          <span className={styles.qAnswerText}>{q.answer}</span>
        </div>
      )}
    </div>
  );
}

/* ──────────────────────────────────────────────
   Step 3 – Review & Publish
────────────────────────────────────────────── */
function ReviewStep({ onBack }) {
  const [questions, setQuestions] = useState(MOCK_QUESTIONS);
  const [published, setPublished] = useState(false);

  const deleteQ = (id) => setQuestions(prev => prev.filter(q => q.id !== id));
  const regenerateQ = (id) => {
    // Mock: shuffle answer to simulate regeneration
    setQuestions(prev => prev.map(q => q.id === id
      ? { ...q, difficulty: ['Easy', 'Medium', 'Hard'][Math.floor(Math.random() * 3)] }
      : q
    ));
  };

  const totalMarks = questions.reduce((sum, q) => sum + q.marks, 0);

  if (published) {
    return (
      <div className={styles.publishedScreen}>
        <div className={styles.publishSuccess}>✅</div>
        <h2>Test Published Successfully!</h2>
        <p>Your assessment is now live and available to students.</p>
        <div className={styles.publishMeta}>
          <span>📋 {questions.length} Questions</span>
          <span>📊 {totalMarks} Marks</span>
          <span>⏱️ 30 min</span>
        </div>
        <div className={styles.publishActions}>
          <Link href="/teacher"><Button variant="primary">← Back to Dashboard</Button></Link>
          <Link href="/teacher/create"><Button variant="secondary">Create Another Test</Button></Link>
        </div>
      </div>
    );
  }

  return (
    <div className={styles.stepContent}>
      <div className={styles.reviewHeader}>
        <div>
          <h2 className={styles.stepTitle}>Review Generated Questions</h2>
          <p className={styles.stepDesc}>
            Gemma generated <strong>{questions.length} questions</strong> worth <strong>{totalMarks} marks</strong>. Edit, delete, or regenerate before publishing.
          </p>
        </div>
        <div className={styles.reviewBadge}>
          <Badge variant="gemma">Powered by Gemma</Badge>
        </div>
      </div>

      {/* Summary row */}
      <div className={styles.reviewSummary}>
        {['MCQ', 'True/False', 'One-liner', 'Brief Answer'].map(type => {
          const count = questions.filter(q => q.type === type).length;
          return count > 0 ? (
            <div key={type} className={styles.reviewSummaryItem}>
              <span className={styles.reviewCount}>{count}</span>
              <span className={styles.reviewType}>{type}</span>
            </div>
          ) : null;
        })}
      </div>

      {/* Questions */}
      <div className={styles.questionList}>
        {questions.map((q, i) => (
          <QuestionCard
            key={q.id}
            q={q}
            index={i}
            onDelete={() => deleteQ(q.id)}
            onRegenerate={() => regenerateQ(q.id)}
          />
        ))}
      </div>

      <div className={styles.stepActions}>
        <Button variant="secondary" onClick={onBack}>← Reconfigure</Button>
        <Button variant="primary" id="publish-test-btn" onClick={() => setPublished(true)}>
          🚀 Publish Test
        </Button>
      </div>
    </div>
  );
}

/* ──────────────────────────────────────────────
   Main Page
────────────────────────────────────────────── */
export default function CreateTestPage() {
  const [step, setStep] = useState(0); // 0=Upload, 1=Config, 2=Generating, 3=Review
  const [wizardStep, setWizardStep] = useState(0); // for StepIndicator (0,1,2)

  const handleStep1Done = () => { setStep(1); setWizardStep(1); };
  const handleStep2Done = () => { setStep(2); }; // triggers Gemma loading
  const handleGenerationDone = () => { setStep(3); setWizardStep(2); };

  return (
    <div className={styles.page}>
      <Navbar />
      <div className={styles.pageBody}>
        {/* Back link */}
        <div className={styles.breadcrumb}>
          <Link href="/teacher" className={styles.backLink}>← Dashboard</Link>
          <span className={styles.breadSep}>/</span>
          <span>Create Test</span>
        </div>

        {/* Step indicator (hidden during Gemma loading) */}
        {step !== 2 && <StepIndicator currentStep={wizardStep} />}

        <div className={styles.card}>
          {step === 0 && <UploadStep onNext={handleStep1Done} />}
          {step === 1 && <ConfigStep onNext={handleStep2Done} onBack={() => { setStep(0); setWizardStep(0); }} />}
          {step === 2 && <GemmaGeneration onDone={handleGenerationDone} />}
          {step === 3 && <ReviewStep onBack={() => { setStep(1); setWizardStep(1); }} />}
        </div>
      </div>
    </div>
  );
}
